name: Build AZenith

on:
  push:
    paths:
      - 'jni/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b

      - name: Build AZenith
        working-directory: jni
        run: |
          ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk \
            APP_PLATFORM=android-24 APP_ABI="arm64-v8a armeabi-v7a"
